[build]
  publish = "public"
  command = '''hugo   --config "config.toml" \
&& hugo   --config "config.toml,config-original.toml"'''

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_THEME = "repo"
#  HUGO_THEMESDIR = "/opt/build"

# [context.production.environment]
#   HUGO_VERSION = "0.80.0"

# [context.deploy-preview.environment]
#   HUGO_VERSION = "0.80.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.80.0"
  
